apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-beamlit-api-token
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  token: {{ .Values.beamlitApiToken | quote }}
