{{ range $i, $e := .Values.allowedNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chart.fullname" $ }}-manager-role
  namespace: {{ $e }}
  labels:
  {{- include "chart.labels" $ | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.beamlit.com
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.beamlit.com
  resources:
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - authorization.beamlit.com
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployment.beamlit.com
  resources:
  - modeldeployments
  - tooldeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployment.beamlit.com
  resources:
  - modeldeployments/finalizers
  - tooldeployments/finalizers
  verbs:
  - update
- apiGroups:
  - deployment.beamlit.com
  resources:
  - modeldeployments/status
  - tooldeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch

---
{{ end }}
{{ range $i, $e := .Values.allowedNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart.fullname" $ }}-manager-rolebinding
  namespace: {{ $e }}
  labels:
  {{- include "chart.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "chart.fullname" $ }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" $ }}-controller-manager'
  namespace: {{ $.Release.Namespace }}
---
{{- end }}