apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-modeldeployment-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - model.beamlit.com
    resources:
      - modeldeployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - model.beamlit.com
    resources:
      - modeldeployments/status
    verbs:
      - get
