# permissions for end users to edit policies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-policy-editor-role
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - beamlit.com
    resources:
      - policies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - beamlit.com
    resources:
      - policies/status
    verbs:
      - get
