# permissions for end users to view tooldeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ include "chart.fullname" . }}-tooldeployment-viewer-role
rules:
- apiGroups:
  - beamlit.com
  resources:
  - tooldeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - beamlit.com
  resources:
  - tooldeployments/status
  verbs:
  - get
