apiVersion: v1
kind: Service
metadata:
  name: {{ include "beamlit-proxy.fullname" . }}
  labels: {{- include "beamlit-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
    - port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector: {{- include "beamlit-proxy.selectorLabels" . | nindent 4 }}
