# permissions for end users to edit modeldeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: modeldeployment-editor-role
rules:
  - apiGroups:
      - model.beamlit.com
    resources:
      - modeldeployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - model.beamlit.com
    resources:
      - modeldeployments/status
    verbs:
      - get
