# permissions for end users to view modeldeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: modeldeployment-viewer-role
rules:
- apiGroups:
  - model.beamlit.io
  resources:
  - modeldeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - model.beamlit.io
  resources:
  - modeldeployments/status
  verbs:
  - get
