# permissions for end users to edit tooldeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: tooldeployment-editor-role
rules:
- apiGroups:
  - beamlit.com
  resources:
  - tooldeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - beamlit.com
  resources:
  - tooldeployments/status
  verbs:
  - get
