apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ModelDeployment is the Schema for the modeldeployments API
      displayName: Model Deployment
      kind: ModelDeployment
      name: modeldeployments.model.beamlit.io
      version: v1alpha1
  description: beamlit operator
  displayName: operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - beamlit
  links:
  - name: Operator
    url: https://operator.domain
  maturity: alpha
  provider:
    name: "beamlit.io\e[C"
  version: 0.0.0
