apiVersion: deployment.beamlit.com/v1alpha1
kind: ModelDeployment
metadata:
  namespace: beamlit
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: test-model-deployment
spec:
  model: "offloading-model"
  environment: "production"
  modelSourceRef:
    apiVersion: apps/v1 # mandatory
    kind: Deployment # mandatory
    name: php-apache # mandatory
    namespace: beamlit # remove
  serviceRef:
    name: php-apache
    namespace: beamlit
    targetPort: 80
  policies:
    - name: policy-sample
      namespace: beamlit
      refType: localPolicy
  offloadingConfig:
    behavior:
      percentage: 50
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 5
