apiVersion: deployment.beamlit.com/v1alpha1
kind: ModelDeployment
metadata:
  namespace: beamlit
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: test-model-deployment
spec:
  model: "offloading-model"
  environment: "production"
  modelSourceRef:
    apiVersion: apps/v1 # mandatory
    kind: Deployment # mandatory
    name: whisper-app # mandatory
    namespace: beamlit # remove
  serviceRef:
    name: whisper-app
    namespace: beamlit
    targetPort: 5000
  offloadingConfig:
    behavior:
      percentage: 50
    metrics:
      - type: External
        external:
          metric:
            name: transcription_duration_seconds_sum
            selector:
              matchLabels:
                job: "whisper-app"
          target:
            type: Value
            value: "2"
