apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app
  labels:
    app: sample-app
  namespace: observability
spec:
  selector:
    matchLabels:
      app: sample-app
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: "8080"
      path: /metrics
      name: http
      interval: 30s
