name: Controller Helm Publish
on:
  push:
    branches:
      - main
jobs:
  publish-helm-chart:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables
        id: set-variables
        run: |
          echo "VERSION=$(yq -r .version ./chart/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Env variable output
        id: test-variables
        run: |
          echo ${{ steps.set-variables.outputs.VERSION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Init dependencies
        run: |
          cd chart
          helm dependency build
          cd ..

      - name: Package and push helm chart
        run: |
          helm package ./chart --version ${{ steps.set-variables.outputs.VERSION }}
          helm push ./beamlit-controller-chart-${{ steps.set-variables.outputs.VERSION }}.tgz oci://ghcr.io/beamlit
